# Generated by Django 2.2.6 on 2019-10-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20191010_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='p_name',
            field=models.CharField(default='입금자명', max_length=30),
        ),
    ]
