# Generated by Django 2.2.6 on 2019-10-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_reservation_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='p_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
