# Generated by Django 2.2.6 on 2019-10-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='password',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
